# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
